name: current_build

on:
  push:
  pull_request:
  page_build:
    release:
      types:
        - created
jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.2', '7.3', '7.4' ]
      fail-fast: false
    env:
      MATRIX_PHP: ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test suite
        run:  vendor/bin/simple-phpunit
