name: current_build

on:
  push:
  pull_request:
  page_build:
    release:
      types:
        - created
jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.2', '7.3', '7.4', '8.0', '8.1' ]
      fail-fast: false
    env:
      MATRIX_PHP: ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: "${{ matrix.php }}"
          tools: composer
          ini-values: error_reporting=-1, display_errors=On

      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: composer update --no-interaction --prefer-dist

      - name: Run test suite
        run:  vendor/bin/simple-phpunit
